"""
ai_writer.py – Claude-powered tweet generation.

Provides three public functions:
  generate_news_tweet(story)         – factual news tweet for a single story
  generate_morning_recap(headlines)  – daily 08:00 UK market-briefing tweet
  generate_quote_tweet(original)     – analyst-voice quote-tweet with context

Voice: professional crypto news analyst (Bloomberg terminal, not Discord alpha).
Report facts and data. No buy/sell calls. No dismissive language. Present both
sides when relevant. Highlight what's notable without making directional calls.

Engagement tweets and contrarian takes are separate scheduled categories and
intentionally use a different voice — they are NOT generated here.

Requires ANTHROPIC_API_KEY in .env.
Falls back to a plain-text summary if the API call fails.
"""

import logging
import time
import anthropic

import config

logger = logging.getLogger(__name__)

_client: anthropic.Anthropic | None = None

# Map CryptoPanic currency codes → canonical hashtags
_HASHTAG_MAP = {
    "BTC": "#Bitcoin",
    "ETH": "#Ethereum",
}
_FALLBACK_HASHTAG = "#Crypto"

MODEL = "claude-haiku-4-5-20251001"

# Shared system prompt for all news/briefing/quote-tweet generation.
# Engagement tweets and contrarian takes use a different voice and are
# scheduled separately — they are not generated by this module.
_ANALYST_SYSTEM = (
    "You are a professional crypto news analyst. "
    "Your job is to report facts and data clearly and concisely. "
    "Do not tell people what to buy, sell, or skip. "
    "Do not insult or dismiss any project. "
    "Present both sides when the data supports it. "
    "You may highlight what is notable or unusual in the data, "
    "but do not make directional calls or speculative judgments. "
    "Write like a Bloomberg terminal, not a crypto Discord. "
    "Be precise, neutral, and informative."
)


def _get_client() -> anthropic.Anthropic:
    global _client
    if _client is None:
        _client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
    return _client


def _pick_hashtags(story: dict) -> str:
    """Return 1-2 hashtags appropriate for the story's currencies."""
    currencies = story.get("currencies") or []
    codes = [c["code"] for c in currencies if c.get("code") and c["code"] != "?"]
    tags = [_HASHTAG_MAP[code] for code in codes if code in _HASHTAG_MAP]
    if not tags:
        tags = [_FALLBACK_HASHTAG]
    return " ".join(tags[:2])


def generate_news_tweet(story: dict) -> str:
    """
    Ask Claude to write a factual news tweet for a single crypto story.
    Reports what happened; no directional calls or hype.
    Ends with 1-2 relevant hashtags (#Bitcoin, #Ethereum, or #Crypto).
    Falls back to a plain formatted string if the API call fails.
    """
    title = story.get("title", "")
    url = story.get("url", "")
    hashtags = _pick_hashtags(story)

    if not config.ANTHROPIC_API_KEY:
        logger.debug("ANTHROPIC_API_KEY not set – using plain news tweet format")
        return _plain_news_tweet(title, url, hashtags)

    prompt = (
        f"Write a concise, factual tweet (max 240 characters) reporting this crypto "
        f"news headline. State what happened and why it matters based on the facts. "
        f"No directional calls, no hype, no dismissive language. "
        f"End with these hashtags: {hashtags}\n\n"
        f"Headline: {title}\n\n"
        f"Output only the tweet text. No quotes, no commentary."
    )

    last_exc: anthropic.APIError | None = None
    for attempt in range(1, 4):
        try:
            message = _get_client().messages.create(
                model=MODEL,
                max_tokens=120,
                system=_ANALYST_SYSTEM,
                messages=[{"role": "user", "content": prompt}],
            )
            tweet = message.content[0].text.strip()
            # Append URL on a new line if it fits
            candidate = f"{tweet}\n{url}" if url else tweet
            if len(candidate) <= 280:
                return candidate
            return tweet[:277 - len(url) - 1].rsplit(" ", 1)[0] + f"…\n{url}" if url else tweet
        except anthropic.APIError as exc:
            last_exc = exc
            logger.warning("Claude API error (attempt %d/3) generating news tweet: %s", attempt, exc)
            if attempt < 3:
                time.sleep(5)

    logger.warning("All 3 attempts failed – falling back to plain tweet")
    return _plain_news_tweet(title, url, hashtags)


def generate_morning_recap(headlines: list[str]) -> str:
    """
    Ask Claude to write a factual morning market briefing tweet (max 220 chars)
    based on the top 3 recent crypto headlines.
    Falls back to a plain bullet summary if the API call fails.
    """
    if not headlines:
        return "☀️ Good morning! Crypto markets are open. Stay sharp. #Crypto"

    numbered = "\n".join(f"{i+1}. {h}" for i, h in enumerate(headlines[:3]))

    if not config.ANTHROPIC_API_KEY:
        logger.debug("ANTHROPIC_API_KEY not set – using plain morning recap format")
        return _plain_morning_recap(headlines)

    prompt = (
        "Write a morning crypto market briefing tweet (max 220 characters). "
        "Start with ☀️. Summarise the key factual themes from the headlines — "
        "what moved, what was announced, what is notable in the data. "
        "No buy/sell signals, no hype. "
        "End with 1-2 relevant hashtags (#Bitcoin, #Ethereum, or #Crypto). "
        "Output only the tweet text. No quotes, no commentary.\n\n"
        f"Today's top headlines:\n{numbered}"
    )

    try:
        message = _get_client().messages.create(
            model=MODEL,
            max_tokens=100,
            system=_ANALYST_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
        )
        tweet = message.content[0].text.strip()
        return tweet[:220]
    except anthropic.APIError as exc:
        logger.warning("Claude API error generating morning recap: %s", exc)
        return _plain_morning_recap(headlines)


def generate_quote_tweet(original_text: str) -> str:
    """
    Ask Claude to write a professional quote-tweet adding factual context.
    No directional calls; presents both sides where relevant.
    Max 220 chars, always ends with ⚠️ NFA.
    Falls back to a plain comment if the API call fails.
    """
    if not config.ANTHROPIC_API_KEY:
        logger.debug("ANTHROPIC_API_KEY not set – using plain quote tweet format")
        return _plain_quote_tweet(original_text)

    prompt = (
        "Write a quote-tweet reply to the tweet below. "
        "Add factual context, data, or relevant background that helps readers "
        "understand what is notable about this. "
        "Do not make directional calls or tell people what to do. "
        "If there are two sides to the story, acknowledge them. "
        "Max 220 characters total. End with ⚠️ NFA on the same line. "
        "Output only the reply text. No quotes, no commentary.\n\n"
        f"Tweet to quote:\n{original_text}"
    )

    try:
        message = _get_client().messages.create(
            model=MODEL,
            max_tokens=100,
            system=_ANALYST_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
        )
        reply = message.content[0].text.strip()
        return reply[:220]
    except anthropic.APIError as exc:
        logger.warning("Claude API error generating quote tweet: %s", exc)
        return _plain_quote_tweet(original_text)


# ── Plain-text fallbacks ──────────────────────────────────────────────────────

def _plain_news_tweet(title: str, url: str, hashtags: str) -> str:
    max_title = 200
    if len(title) > max_title:
        title = title[:max_title - 1] + "…"
    parts = [f"📰 {title}", url, hashtags]
    return "\n".join(p for p in parts if p)


def _plain_morning_recap(headlines: list[str]) -> str:
    intro = "☀️ Morning crypto update:"
    items = " | ".join(h[:60] for h in headlines[:3])
    tweet = f"{intro} {items} #Crypto"
    return tweet[:220]


def _plain_quote_tweet(original_text: str) -> str:
    snippet = original_text[:80].rsplit(" ", 1)[0] + "…" if len(original_text) > 80 else original_text
    return f"Worth watching — {snippet} ⚠️ NFA"
